# Application Name
spring.application.name=api-gateway

# Gateway Port
server.port=8070

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable service discovery based routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# JWT Secret
# Same secret must be used in auth-service also
jwt.secret=myfinbank_super_secret_key_2026_myfinbank_secure_token_key


# Auth Service Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Loan Service Route
spring.cloud.gateway.routes[1].id=loan-service
spring.cloud.gateway.routes[1].uri=lb://LOAN-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/loans/**,/documents/**

# EMI Service Route
spring.cloud.gateway.routes[2].id=emi-service
spring.cloud.gateway.routes[2].uri=lb://EMI-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/emi/**

# Workflow Service Route
spring.cloud.gateway.routes[3].id=workflow-service
spring.cloud.gateway.routes[3].uri=lb://WORKFLOW-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/workflow/**

# Logging
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO